### ISSUE TITLE
🗄️ DNS provider suggestion | NixNet

### ISSUE THREAD

**Issue by Mikaela** [privacytools/privacytools.io#1206]
## Basic Information

**Name:** NixNet
**Filtering:** No
**Privacy policy:** https://nixnet.xyz/privacy/
**Protocols:** DoT (853)
**Server/Location:** Anycast, Luxembourg, New York, Las Vegas
**Source:** - (Unbound)
**Type:** Informal collective (part of Librehosters, see #816 )
**Website:** https://nixnet.xyz/dns/

## Description

From what I understood they are smaller indepedent provider and thus good for decentralization. They also have servers in the US which our listing is currently missing.

I opened an issue about features I am unsure of: https://git.nixnet.xyz/NixNet/NixNet/issues/2 (including whether IP addresses get logged)

### Required features:

* [x] supports DoH or DoT 
* [x] supports DNSSEC 
* [x] doesn't log IP addresses during normal operation 

#### Desired features

* [x] supports QNAME minimization

**Comment by Mikaela** [comment]
They also recommend [lelux.fi](https://lelux.fi/resolver/) which leaves some details unclear to me, but I get the picture that [they don't support DNSSEC](https://wiki.lelux.fi/dns-over-tls/unbound/linux/#arch), so I am not opening an issue for now.

**Comment by Perflyst** [comment]
poke @amolith

**Comment by ProgressiveArchitect** [comment]
It seems silly to add another DNS server to an already packed list, especially when it doesn't support all the features that would make it fully privacy focused.

**Comment by Amolith** [comment]
@ProgressiveArchitect I plan to implement those features in the near future though I just started at uni and don't have much time. I'll keep this thread updated with my progress.

**Comment by Amolith** [comment]
### TODO

- [x] DNSSEC validation
- [x] Check QNAME minimization
- [x] Explain Unbound verbosity in privacy policy

I set these up a while ago and I couldn't remember what I had configured. As I was looking around, I found that all the features requested are enabled; Unbound does DNSSEC validation and QNAME minimisation by default. I've added a new header on the [DNS page](https://nixnet.xyz/dns) with a list of the features as well as mentioned the Unbound verbosity in the [Privacy Policy](https://nixnet.xyz/privacy)

**Comment by Amolith** [comment]
Adblocked DoH is active and uncensored is in progress.
https://nixnet.xyz/dns/

**Comment by Mikaela** [comment]
Thanks for the update (and https://github.com/privacytoolsIO/privacytools.io/pull/1321).

Is Anycast DoH missing on purpose? I see that only Adblock anycast has DoH listed.

**Comment by Amolith** [comment]
The first Anycast section is DNS without Adblock (uncensored) and that's what I'm working on implementing DoH with. You'll notice that the specific locations only list that as well and not uncensored.

**Comment by Amolith** [comment]
I'm in the process of moving all of my documentation to a new website; DNS information can be found [here](https://docs.nixnet.services/en/dns) with relevant links to other sections. I have git set up for the backend so all the pages are plain MD files stored on [Gitea](https://git.nixnet.xyz/NixNet/documentation)

**Comment by Amolith** [comment]
Change of URL again (sorry!); I switched from [Wiki.js](https://wiki.js.org/) to [MediaWiki](https://www.mediawiki.org/) because the former relies to heavily on JS and this information needs to be accessible to anyone. Most information can be found [here](https://docs.nixnet.services/DNS) but the privacy policy is on a [separate page](https://docs.nixnet.services/DNS_(privacy)). I'm going to set them all up with proper categories in the near future.

**Comment by blacklight447-ptio** [comment]
> 
> 
> Change of URL again (sorry!); I switched from [Wiki.js](https://wiki.js.org/) to [MediaWiki](https://www.mediawiki.org/) because the former relies to heavily on JS 


*shocked pikachu face*
